openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "HSL Map project Documentation"
  description: "Documents HSL Map project API endpoints"
servers:
  - url: "https://dev.kartat.hsl.fi/"
    description: "HSL Karttatuotanto Dev Environment"
  - url: "https://kartat.hsl.fi/"
    description: "HSL Karttatuotanto Prod Environment"

components:
  schemas:
    Timetable:
      properties:
        component: 
          type: string
          default: "Timetable"
          description: "Render a Stop timetable"
        props:
          type: object
          properties:
            stopId:
              type: string
              default: '1010109'
            date:
              type: string
              default: '2024-03-28'
            isSummerTimetable:
              type: boolean
              default: false
            printTimetablesAsA4:
              type: boolean
            printTimetablesAsGreyscale:
              type: boolean
              default: false
            template:
              type: string
              default: 'default'
            routeFilter:
              type: string
              description: 'Route filtering works by filtering out the lines sent with this parameter. For example if lines 7, 8 and 9 would belong to this stops timetable this filter would make the timetable only display route 9 in the timetable' 
              default: '7, 8'
            showAddressInfo: 
              type: boolean
              default: false
              description: 'Show address info on the rendered timetable'
            redirect:
              type: boolean
              default: false
              description: 'When enabled, responds with a redirect response instead of the url in the response body for example for allowing the developer to guide the end-user directly into the rendering page when embedding this functionality onto another page.'
    LineTimetable:
      properties:
        component: 
          type: string
          default: "LineTimetable"
          description: "Render a Line timetable"
        props:
          type: object
          properties:
            lineId:
              type: string
              default: '2015'
              description: 'Line ID string'
              required: true
            dateBegin:
              type: string
              default: '1999-02-02'
              description: 'The starting date of the line. Used to filter the correct line from JORE data. If dates are omitted, the endpoint returns line timetables for the current week.'
              required: false
            dateEnd:
              type: string
              default: '2050-12-31'
              description: 'The end date of the line. Used to filter the correct line from JORE data. If dates are omitted, the endpoint returns line timetables for the current week.'
              required: false
            showPrintButton: 
              type: boolean
              default: false
              description: 'Show a print button on the rendered timetable'
              required: false
            lang: 
              type: string
              enum: [fi, sv, en]
              default: fi
              description: "Change the 'print schedule' button's language"
              required: false
            redirect:
                type: boolean
                default: false
                description: 'When enabled, responds with a redirect response instead of the url in the response body for example for allowing the developer to guide the end-user directly into the rendering page when embedding this functionality onto another page.'
                required: false

paths:
  /julkaisin-api/generateRenderUrl:
    post:
      summary: "Generate a render url for timetable rendering"
      tags:
        - Map Publisher
      requestBody:
        description: Includes the `component` and the `props` for the selected timetable type.
        required: true
        content:
          Timetable (application/json):
            schema:
              $ref: '#/components/schemas/Timetable'
          LineTimetable (application/json):
            schema:
              $ref: '#/components/schemas/LineTimetable'
                  
      responses:
        400:
          description: "Bad request"
        200:
          description: "OK"
          content:
            Timetable (application/json):
              schema:
                example: { renderUrl: "https://dev.kartat.hsl.fi/julkaisin-render/?component=Timetable&props%5BstopId%5D=1010109&props%5Bdate%5D=2024-03-28&props%5BisSummerTimetable%5D=false&props%5BprintTimetablesAsA4%5D=true&props%5BprintTimetablesAsGreyscale%5D=false&props%5Btemplate%5D=default&props%5BshowAddressInfo%5D=false&props%5BshowPrintButton%5D=true&props%5Bredirect%5D=false&props%5Blang%5D=fi" }
            LineTimetable (application/json):
              schema:
                example: { renderUrl: "https://dev.kartat.hsl.fi/julkaisin-render/?component=LineTimetable&props%5BlineId%5D=2015&props%5BdateBegin%5D=2024-12-01&props%5BdateEnd%5D=2024-12-31&props%5BshowPrintButton%5D=true&props%5Blang%5D=fi&props%5Bredirect%5D=false" }
  
  /julkaisin-api/weeklyLineTimetable/:lineId:
    get:
      summary: "Weekly Line Timetable endpoint"
      tags:
        - Map Publisher
      parameters:
        - in: path
          name: lineId
          required: true
          schema:
            type: string
            example: '2015'
            description: 'Line ID string'
        - in: query
          name: redirect
          required: false
          schema:
            type: boolean
            example: false
            default: false
            description: 'When enabled, responds with a redirect response instead of the url in the response body for example for allowing the developer to guide the end-user directly into the rendering page when embedding this functionality onto another page.'
        - in: query
          name: showPrintButton
          required: false
          schema:
            type: boolean
            example: false
            default: false
            description: 'Show a "print timetable" button on the rendered timetable'
        - in: query
          name: lang
          required: false
          schema:
            type: string
            example: 'fi/sv/en'
            default: 'fi'
            description: 'Change the "print schedule" button language'
      responses:
        400:
          description: "Bad request"
        200:
          description: "OK"
          content:
              LineTimetable (application/json):
                schema:
                example: { renderUrl: "https://dev.kartat.hsl.fi/julkaisin-render/?component=LineTimetable&props%5BlineId%5D=2015&props%5BdateBegin%5D=2024-12-01&props%5BdateEnd%5D=2024-12-31&props%5BshowPrintButton%5D=true&props%5Blang%5D=fi&props%5Bredirect%5D=false" }
  
  /jore/tiles/{layer}/index.json:
    get:
      summary: "TileJSON info endpoint for a layer"
      tags:
        - JORE Tileserver
      parameters:
        - in: path
          name: layer
          required: true
          schema:
            type: string
            enum: ['stops', 'routes', 'terminals', 'regular-routes', 'regular-stops', 'near-bus-routes', 'near-bus-stops', 'stops-by-routes']
            example: stops
      responses:
        200:
          description: "Returns TileJSON info of the requested layer"
          content:
            application/json:
              schema:
                example: {"tilejson":"2.2.0","tiles":["https://dev.kartat.hsl.fi/jore/tiles/stops/{z}/{x}/{y}.pbf"]}
  
  /jore/tiles/{layer}/{x}/{y}/{z}.pbf:
    get:
      summary: "Tile endpoint for selected layer"
      tags:
        - JORE Tileserver
      parameters:
        - in: path
          name: layer
          required: true
          schema:
            type: string
            enum: ['stops', 'routes', 'terminals', 'regular-routes', 'regular-stops', 'near-bus-routes', 'near-bus-stops', 'stops-by-routes']
            example: stops
        - in: path
          name: x
          required: true
          schema:
            type: integer
            example: 60
            minimum: 2
        - in: path
          name: y
          required: true
          schema:
            type: integer
            example: 24
            minimum: 2
        - in: path
          name: z
          required: true
          schema:
            type: integer
            example: 14
            minimum: 1
      responses:
        200:
          description: "Returns a PBF tile from the coordinates"
  
  
