openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Swagger UI Webpack Setup"
  description: "Demonstrates Swagger UI with Webpack including CSS and OAuth"
servers:
  - url: "https://dev.kartat.hsl.fi/"
    description: "HSL Karttatuotanto DEV Environment"

components:
  securitySchemes:
    identity_server_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "https://demo.identityserver.io/connect/authorize"
          scopes:
            api: "api"
  schemas:
    Timetable:
      properties:
        props:
          type: object
          properties:
            stopId:
              type: string
            date:
              type: string
            isSummerTimetable:
              type: boolean
              default: false
            printTimetablesAsA4:
              type: boolean
            printTimetablesAsGreyscale:
              type: boolean
              default: false
            template:
              type: string
              default: 'default'

paths:
  /julkaisin-render/generateRenderUrl:
    post:
      summary: "Generate a render url for timetable rendering"
      tags:
        - Map Publisher
      requestBody:
        description: Properties for the timetable to render
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Timetable'
      responses:
        400:
          description: "Bad request"
        200:
          description: "OK"
          content:
            application/json:
              schema:
                example: { renderUrl: "https://dev.kartat.hsl.fi/julkaisin-render/?component=Timetable&props%5BstopId%5D=1010109&props%5Bdate%5D=2023-05-06" }
  
